name: flutter_mobile_o11y_demo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  confetti: ^0.8.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  faro: ^0.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^16.0.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  riverpod_annotation: ^2.3.5
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.1.1

flutter:
  assets:
    - .env
    - assets/images/

  uses-material-design: true
